In [2]:
import pandas as pd
df = pd.read_pickle('../../data/processed/10_cleaned_master_data.pkl')


display(df.head(3))

print(df.columns.tolist())

,race,year,url,rank,rider_url,time_gap,birthdate,height,name,nationality,...,departure_wind_mittel,departure_luftfeuchte_mittel,departure_niederschlag_mittel,departure_windrichtung_mittel,arrival_temp_mittel,arrival_regen_mittel,arrival_wind_mittel,arrival_luftfeuchte_mittel,arrival_niederschlag_mittel,arrival_windrichtung_mittel
0,tour-de-france,2005,https://www.procyclingstats.com/race/tour-de-f...,1.0,david-zabriskie,20:5120:51,1979-01-12,1.83,David Zabriskie,US,...,12.0,75.25,0.0,214.25,20.62,0.0,11.55,74.0,0.0,218.25
1,tour-de-france,2005,https://www.procyclingstats.com/race/tour-de-f...,2.0,lance-armstrong,0:020:02,1971-09-18,1.78,Lance Armstrong,US,...,12.0,75.25,0.0,214.25,20.62,0.0,11.55,74.0,0.0,218.25
2,tour-de-france,2005,https://www.procyclingstats.com/race/tour-de-f...,3.0,alexandr-vinokourov,0:530:53,1973-09-16,1.77,Alexandr Vinokurov,KZ,...,12.0,75.25,0.0,214.25,20.62,0.0,11.55,74.0,0.0,218.25

['race', 'year', 'url', 'rank', 'rider_url', 'time_gap', 'birthdate', 'height', 'name', 'nationality', 'weight', 'url_name', 'departure', 'arrival', 'distance', 'vertical_meters', 'profile_score', 'won_how', 'avg_speed', 'race_ranking', 'one_day_races', 'gc', 'time_trial', 'sprint', 'climber', 'hills', 'stage_nr', 'date', 'departure_lat', 'departure_lon', 'arrival_lat', 'arrival_lon', 'rider_points_season', 'rider_rank_season', 'current_team', 'team_class', 'departure_temp_mittel', 'departure_regen_mittel', 'departure_wind_mittel', 'departure_luftfeuchte_mittel', 'departure_niederschlag_mittel', 'departure_windrichtung_mittel', 'arrival_temp_mittel', 'arrival_regen_mittel', 'arrival_wind_mittel', 'arrival_luftfeuchte_mittel', 'arrival_niederschlag_mittel', 'arrival_windrichtung_mittel']

In [5]:
print(df['name'].isna().sum())
#2874 Fahrernamen Zeilen na

df.loc[df['name'].isna(),['year', 'race', 'stage_nr', 'rank', 'url']].sort_values(by='rank').head(30)
#komplette Liste
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#  display(df.loc[df['name'].isna(),['year', 'race', 'stage_nr', 'rank', 'url']].sort_values(by='rank'))

2874

,year,race,stage_nr,rank,url
147847,2025,giro-d-italia,4,1.0,https://www.procyclingstats.com/race/giro-d-it...
76353,2005,giro-d-italia,7,1.0,https://www.procyclingstats.com/race/giro-d-it...
153278,2005,vuelta-a-espana,14,1.0,https://www.procyclingstats.com/race/vuelta-a-...
149255,2025,giro-d-italia,12,2.0,https://www.procyclingstats.com/race/giro-d-it...
153852,2005,vuelta-a-espana,18,2.0,https://www.procyclingstats.com/race/vuelta-a-...
77284,2005,giro-d-italia,12,2.0,https://www.procyclingstats.com/race/giro-d-it...
70993,2024,tour-de-france,18,2.0,https://www.procyclingstats.com/race/tour-de-f...
153427,2005,vuelta-a-espana,15,3.0,https://www.procyclingstats.com/race/vuelta-a-...
153992,2005,vuelta-a-espana,19,4.0,https://www.procyclingstats.com/race/vuelta-a-...
150273,2025,giro-d-italia,18,4.0,https://www.procyclingstats.com/race/giro-d-it...
83313,2007,giro-d-italia,6,5.0,https://www.procyclingstats.com/race/giro-d-it...
167658,2009,vuelta-a-espana,17,5.0,https://www.procyclingstats.com/race/vuelta-a-...
151309,2005,vuelta-a-espana,3,5.0,https://www.procyclingstats.com/race/vuelta-a-...
141495,2023,giro-d-italia,5,5.0,https://www.procyclingstats.com/race/giro-d-it...
209872,2021,vuelta-a-espana,8,5.0,https://www.procyclingstats.com/race/vuelta-a-...
6598,2006,tour-de-france,19,5.0,https://www.procyclingstats.com/race/tour-de-f...
167504,2009,vuelta-a-espana,16,5.0,https://www.procyclingstats.com/race/vuelta-a-...
151113,2005,vuelta-a-espana,2,6.0,https://www.procyclingstats.com/race/vuelta-a-...
80313,2006,giro-d-italia,9,6.0,https://www.procyclingstats.com/race/giro-d-it...
151700,2005,vuelta-a-espana,5,6.0,https://www.procyclingstats.com/race/vuelta-a-...
82191,2006,giro-d-italia,20,6.0,https://www.procyclingstats.com/race/giro-d-it...
76732,2005,giro-d-italia,9,6.0,https://www.procyclingstats.com/race/giro-d-it...
77822,2005,giro-d-italia,15,6.0,https://www.procyclingstats.com/race/giro-d-it...
78609,2005,giro-d-italia,20,6.0,https://www.procyclingstats.com/race/giro-d-it...
223457,2025,vuelta-a-espana,8,7.0,https://www.procyclingstats.com/race/vuelta-a-...
153995,2005,vuelta-a-espana,19,7.0,https://www.procyclingstats.com/race/vuelta-a-...
212320,2022,vuelta-a-espana,2,7.0,https://www.procyclingstats.com/race/vuelta-a-...
222743,2025,vuelta-a-espana,4,7.0,https://www.procyclingstats.com/race/vuelta-a-...
210735,2021,vuelta-a-espana,13,7.0,https://www.procyclingstats.com/race/vuelta-a-...
73191,2025,tour-de-france,10,7.0,https://www.procyclingstats.com/race/tour-de-f...

In [6]:
# 1. Wir erstellen eine Teilmenge, die nur die Zeilen mit fehlenden Namen enthält
df_nas = df[df['name'].isna()]

print("=== 1. JAHRE MIT DEN MEISTEN NA-WERTEN ===")
display(df_nas['year'].value_counts().head(20))

print("\n=== 2. RENNEN MIT DEN MEISTEN NA-WERTEN ===")
display(df_nas['race'].value_counts().head(20))

print("\n=== 3. PLATZIERUNGEN (RANK) MIT DEN MEISTEN NA-WERTEN ===")
# Hier sehen wir, ob z.B. bestimmte Platzierungen (wie 'DNF' oder 'DNS') oft keinen Namen haben
display(df_nas['rank'].value_counts().head(20))

print("\n=== 4. KOMBINATION: WELCHE JAHRE + RENNEN SIND AM STÄRKSTEN BETROFFEN? ===")
# Gruppierung nach Jahr und Rennen, um systematische Fehler (z.B. ein komplett fehlendes Jahr bei einem Rennen) zu finden
kombi_stats = df_nas.groupby(['year', 'race', 'stage_nr']).size().reset_index(name='Anzahl_Missing_Names')
kombi_stats = kombi_stats.sort_values(by='Anzahl_Missing_Names', ascending=False)

# Anzeige der Top 20 betroffenen Jahr-Rennen-Kombinationen
display(kombi_stats.head(20))

=== 1. JAHRE MIT DEN MEISTEN NA-WERTEN ===

year
2025    528
2005    495
2007    400
2006    362
2008    247
2009    235
2024    126
2022    111
2023     92
2012     42
2010     42
2020     39
2021     38
2018     21
2019     21
2013     20
2015     20
2011     18
2016     17
Name: count, dtype: int64

=== 2. RENNEN MIT DEN MEISTEN NA-WERTEN ===

race
vuelta-a-espana    1705
giro-d-italia      1060
tour-de-france      109
Name: count, dtype: int64

=== 3. PLATZIERUNGEN (RANK) MIT DEN MEISTEN NA-WERTEN ===

rank
118.0    31
131.0    30
142.0    29
133.0    29
158.0    28
127.0    28
126.0    28
121.0    28
149.0    27
98.0     27
124.0    27
111.0    26
114.0    26
135.0    26
113.0    26
110.0    26
86.0     25
116.0    25
130.0    25
137.0    25
Name: count, dtype: int64

=== 4. KOMBINATION: WELCHE JAHRE + RENNEN SIND AM STÄRKSTEN BETROFFEN? ===

     year             race  stage_nr  Anzahl_Missing_Names
20   2005  vuelta-a-espana         1                    17
21   2005  vuelta-a-espana         2                    17
632  2025  vuelta-a-espana         2                    16
631  2025  vuelta-a-espana         1                    16
635  2025  vuelta-a-espana         5                    16
22   2005  vuelta-a-espana         3                    16
23   2005  vuelta-a-espana         4                    16
638  2025  vuelta-a-espana         8                    16
636  2025  vuelta-a-espana         6                    16
633  2025  vuelta-a-espana         3                    16
637  2025  vuelta-a-espana         7                    16
634  2025  vuelta-a-espana         4                    16
640  2025  vuelta-a-espana        10                    15
639  2025  vuelta-a-espana         9                    15
25   2005  vuelta-a-espana         6                    15
24   2005  vuelta-a-espana         5                    15
641  2025  vuelta-a-espana        11                    14
647  2025  vuelta-a-espana        17                    14
646  2025  vuelta-a-espana        16                    14
644  2025  vuelta-a-espana        14                    14

In [7]:
# droppen aller Zeilen mit name = na
# Siehe src/scraping/code/03_test_drivers_missing.py

# Einige Profile wurden nicht richtig gescraped
# wichtigsten Fahrer haben wir jedoch beibehalten

df_final = df.dropna(subset=['name'])
print(f"Zeilen vor dem Bereinigen: {len(df)}")
print(f"Zeilen nach dem Bereinigen: {len(df)}")
print(f"Gelöschte Zeilen (NaNs): {len(df) - len(df_final)}")

pfad = '../../data/processed/11_cleaned_master_data.pkl'
df_final.to_pickle(pfad)

Zeilen vor dem Bereinigen: 225692
Zeilen nach dem Bereinigen: 225692
Gelöschte Zeilen (NaNs): 2874

In [9]:
df_final.isna().sum()

race                                0
year                                0
url                                 0
rank                             2785
rider_url                           0
time_gap                            0
birthdate                           0
height                           1058
name                                0
nationality                         0
weight                           1058
url_name                            0
departure                           0
arrival                             0
distance                            0
vertical_meters                  5235
profile_score                    5235
won_how                             0
avg_speed                         140
race_ranking                        0
one_day_races                       0
gc                                  0
time_trial                          0
sprint                              0
climber                             0
hills                               0
stage_nr                            0
date                                0
departure_lat                       0
departure_lon                       0
arrival_lat                         0
arrival_lon                         0
rider_points_season              1888
rider_rank_season                1888
current_team                     3492
team_class                       3492
departure_temp_mittel               0
departure_regen_mittel              0
departure_wind_mittel               0
departure_luftfeuchte_mittel        0
departure_niederschlag_mittel       0
departure_windrichtung_mittel       0
arrival_temp_mittel                 0
arrival_regen_mittel                0
arrival_wind_mittel                 0
arrival_luftfeuchte_mittel          0
arrival_niederschlag_mittel         0
arrival_windrichtung_mittel         0
dtype: int64